### PR TITLE
Trying to add Windows support. Using dnspython library.

### PR DESCRIPTION
**Pull request by sg3-141-592**
I've had a go at adding Windows support to this tool. I used a python library [dnspython](https://pypi.org/project/dnspython/) to replace the use of the `host` command through the shell for doing DNS lookups. I get identical results between running on Linux using `host` and running on Windows with the library.

``` python
res = resolver.Resolver()
res.nameservers = [nameserver]

for name in names:
	try:
		res.query(name)
		# If no exception is thrown, save it as a valid DNS name and send to callback
		# if defined.
		valid_names.append(name)
		if callback:
			callback(name)
	except:
		# Name cannot be found, continue
		pass 
```

Performance is bad, I've not implemented any threading currently. The dnspython library is listed as thread safe but I'm not sure what the cleanest way to add some threading or async running support would be given the different levels of support for things like async across Python versions.

At the moment there's a little switch at the start of `fast_dns_lookup` which checks the OS version, and if its Windows redirects to the `python_dns_lookup` implementation.

``` python
# If we are running on windows use the python dns library instead
if os.name == 'nt':
    return python_dns_lookup(names, nameserver, callback)
```

There's also a minor fix that **requests** is missing from `requirements.txt` currently.

Big fan of the tool, it's been really useful to audit some of my sites. Really easy to use.

### CODE REVIEW

**Comment by initstring** [comment]
Hi @sg3-141-592 !

Thanks so much for taking the time to submit a thoughtful, detailed PR like this.

I want to give this some detailed feedback but need to ponder a bit. This week is a bit hectic for me, but it should slow down after next weekend. Just some thoughts off the top of my head for now:

I'm iffy on adding the extra libraries and complexity to support Windows users, which I am assuming is a very small percentage of people who use the tool. Also I don't actually keep Windows installs around, so this makes testing or dealing with future issues not super easy.

Let me put this one on pause and get back to you.

Again, I do really appreciate the submission! Sorry if this is a bummer of a response. :/

**Comment by sg3-141-592** [comment]
That;s alright, and to be honest when I tried to run it on Windows and got the 'host' command error I just moved it over to Windows Subsystem for Linux and it started working. So I imagine the vast majority of people who want to run it have a way of running it.

One option would be to drop the use of the host command in favour for dnspython, but there'd be some rework associated. I'd say that a CI job might help with some of the cross platform questions but this type of tool is a hard thing to write a CI job for. What you're scanning is a bit of a moving target.

I don't mind if you want to keep it *nix targets only for now, just noticed the host command being used and was interested whether there was a Python equivalent that could be dropped in.

**Comment by initstring** [comment]
I thought a bit more, and I think you're approach is actually the best. I've implemented your function with some tweaks and threading.

@sg3-141-592 would you mind horribly taking a look at https://github.com/initstring/cloud_enum/tree/dns-testing and seeing what you think?

My initial thought is that perhaps I should allow for specifying different thread numbers for HTTP and DNS, as lots of DNS is usually safe and won't get you blocked (I think). As opposed to HTTP which will silently ban with too many.

**Comment by sg3-141-592** [comment]
Sure. I've had a test on Windows. I used a fresh Virtual Environment so I can confirm your `requirements.txt` is all good.

All of the results are coming back correctly and performance is much improved with the threading. A few example data points. Scaling's not very linear, so as you say I'm probably hitting some rate limiting. Sorry I don't have the expertise to say whether its worth your time to try and separate out DNS and HTTP request rates, not something I know a lot about.

- 10 Threads - 113 seconds
- 25 Threads - 95 seconds

The use of ThreadPool looks quite elegant, I don't have any specific code comments it looks good, and I've played with some different combinations of thread numbers and it works fine.

I was wondering what you think about adding a quick fix on the print callbacks? You use ANSI escape sequences which aren't enabled by default in the Windows Powershell or Command Line. They work fine for me on the standard Ubuntu shell but they have trouble on Windows.
image

I've had a look at a fix and the simplest I can find is including the [colorama](https://pypi.org/project/colorama/) library that does cross platform terminal colours. And adding the code snippet below fixes the colours on Powershell and Command Line. No need to update the `utils.printc`.

``` python 
import colorama
colorama.init()
```

image

Completely up to you whether you want to take on another library, but it might be a nice extra to bundle with the dnspython change.

**Comment by initstring** [comment]
Thanks for testing and the feedback!

Let me look into that library this week and will updated as soon as I can.

Your help is much appreciated, have a great day!

**Comment by initstring** [comment]
What do you think of this? https://github.com/initstring/cloud_enum/commit/eef805f849ed3b3ea3b9d8c955983397980a0178

It would mean Windows users would need to manually install the library, but at least it tips them off. A good compromise, maybe?

Would you mind testing?

**Comment by sg3-141-592** [comment]
Sure, just given it a go on a fresh virtual environment and its working. I think its looking good to go.

image

**Comment by initstring** [comment]
Thanks again! This is all merged to master. Your help is very much appreciated!

**Pull request merged**
