### PR TITLE
Add additional URLs to Azure storage accounts check

### PR DESCRIPTION
**Pull request by Ocel0tSec**

### CODE REVIEW

**Comment by initstring** [comment]
Hi @Ocel0tSec - thanks for this contribution!

Can you please provide some context? I see you are appending these URLs to the `check_storage_accounts` function. Do they behave in the exact same manner, including the multi-step enumeration of accounts first and then containers within?

And are they unique? Meaning there will exist a storage container inside an account in one of these new URLs, and not within the old URL?

Can you please provide some working examples, including the HTTP response code body?

Adding these URLs will add significant overhead to the scans, so I'm just trying to understand the impact.

Thanks!

**Comment by Ocel0tSec** [comment]
Hey @initstring great questions! 
Just got back from holiday. I was just going through the Azure documentation on those accounts which gave me the idea and am not 100% sure how they function. https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview. Was hoping to run into a client using one of the newer URLs but haven't ran into one yet. I will prob end up spinning something up once I have some time to refresh my Azure dev account and will update you once I get some better details.

**Comment by initstring** [comment]
Thanks @Ocel0tSec! Keep me posted. I'll leave this PR open for now.

**Comment by initstring** [comment]
I'm going to close this PR, please re-open if you have some more research to share.
Thanks!

**Pull request closed without merging**
